added selenium support, initAndIngestTest and MyDataPageTest
open-metadata/openmetadata-selenium pull request #1
Opened 2021-10-06 14:29 UTC by parthp2107

2021-10-07 05:25 UTC, shahsank3t requested changes

2021-10-07 05:25 UTC, shahsank3t commented on pom.xml
> +<!--        <dependency>-->
Remove the unwanted code instead of commenting out if there's no reason for it.

2021-10-07 05:25 UTC, shahsank3t commented on selenium.properties
> +path = "/Users/parthpanchal/Documents/CodeBase"
use a proper naming convention. is this the root path/directory of this selenium codebase or OpenMetadata codebase or what?

2021-10-07 05:25 UTC, shahsank3t commented on src/main/java/org/openmetadata/selenium/properties/Property.java
> +        PATH = properties.getProperty("path");
property names should be static/constant variables and not be used directly.

2021-10-07 05:25 UTC, shahsank3t commented on src/test/java/org/openmetadata/selenium/pages/MyDataPageTest.java
> +        webDriver.get("http://localhost:8585");
This URL should come from the property file as one might decide to change the url:port anytime.

2021-10-07 05:25 UTC, shahsank3t commented on testng.xml
> +    <suite name = "Suite1">
Give proper name to suite

2021-10-07 05:25 UTC, shahsank3t commented on testng.xml
> +        <test name="Test1">
Give proper name to test

2021-10-08 05:59 UTC, parthp2107 commented on pom.xml
> +<!--        <dependency>-->
Addressed in latest commit

2021-10-08 05:59 UTC, parthp2107 commented on selenium.properties
> +path = "/Users/parthpanchal/Documents/CodeBase"
Addressed in latest commit

2021-10-08 05:59 UTC, parthp2107 commented on src/main/java/org/openmetadata/selenium/properties/Property.java
> +        PATH = properties.getProperty("path");
Addressed in latest commit

2021-10-08 05:59 UTC, parthp2107 commented on src/test/java/org/openmetadata/selenium/pages/MyDataPageTest.java
> +        webDriver.get("http://localhost:8585");
Addressed in latest commit

2021-10-08 05:59 UTC, parthp2107 commented on testng.xml
> +    <suite name = "Suite1">
Addressed in latest commit

2021-10-08 05:59 UTC, parthp2107 commented on testng.xml
> +        <test name="Test1">
Addressed in latest commit

2021-10-08 06:18 UTC, shahsank3t approved these changes

2021-10-08 06:18 UTC, merged